name: Critical Path Check

on:
  pull_request:
    types: [opened, edited, synchronize]
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC

jobs:
  check-critical-path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Critical Path Check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            // Read the check script
            const scriptPath = './scripts/critical_path_check.js';
            if (!fs.existsSync(scriptPath)) {
              console.log('Critical path check script not found, skipping...');
              return;
            }

            const checkScript = require(scriptPath);
            await checkScript({ github, context });

      - name: Comment on PR if check fails
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.pull_request) {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `⚠️ **Critical Path Check Failed**\n\nPlease answer the question: "Is this effort on the critical path to getting a functional MVP on Render.com?"\n\nCheck the checkbox in the PR description and provide an explanation.`
              });
            }
